import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './design-system/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      spacing: {
        1:  'var(--space-1)',
        2:  'var(--space-2)',
        3:  'var(--space-3)',
        4:  'var(--space-4)',
        5:  'var(--space-5)',
        6:  'var(--space-6)',
        8:  'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        section: 'var(--space-section-y)',
      },
      borderColor: {
        DEFAULT: 'var(--neutral-border)',
        subtle: 'var(--neutral-border-subtle)',
        strong: 'var(--neutral-border-strong)',
        card: 'var(--surface-card-border)',
        'card-hover': 'var(--surface-card-border-hover)',
        divider: 'var(--surface-divider)',
      },
      colors: {
        brand: {
          50:  'var(--brand-50)',
          100: 'var(--brand-100)',
          200: 'var(--brand-200)',
          300: 'var(--brand-300)',
          400: 'var(--brand-400)',
          500: 'var(--brand-500)',
          600: 'var(--brand-600)',
          700: 'var(--brand-700)',
          800: 'var(--brand-800)',
          900: 'var(--brand-900)',
          950: 'var(--brand-950)',
          DEFAULT: 'var(--brand-primary)',
          hover: 'var(--brand-primary-hover)',
          active: 'var(--brand-primary-active)',
          subtle: 'var(--brand-primary-subtle)',
          muted: 'var(--brand-primary-muted)',
          'muted-strong': 'var(--brand-primary-muted-strong)',
          border: 'var(--brand-primary-border)',
          'border-subtle': 'var(--brand-primary-border-subtle)',
          'on-dark': 'var(--brand-on-dark)',
          'on-dark-hover': 'var(--brand-on-dark-hover)',
          text: 'var(--brand-text-accent)',
          'text-hover': 'var(--brand-text-accent-hover)',
        },
        neutral: {
          50:  'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
          950: 'var(--neutral-950)',
          bg: 'var(--neutral-bg)',
          'bg-subtle': 'var(--neutral-bg-subtle)',
          'bg-muted': 'var(--neutral-bg-muted)',
          'bg-elevated': 'var(--neutral-bg-elevated)',
          'bg-sunken': 'var(--neutral-bg-sunken)',
          'bg-inverse': 'var(--neutral-bg-inverse)',
          'text-primary': 'var(--neutral-text-primary)',
          'text-secondary': 'var(--neutral-text-secondary)',
          'text-muted': 'var(--neutral-text-muted)',
          'text-subtle': 'var(--neutral-text-subtle)',
          'text-inverse': 'var(--neutral-text-inverse)',
          border: 'var(--neutral-border)',
          'border-subtle': 'var(--neutral-border-subtle)',
          'border-strong': 'var(--neutral-border-strong)',
        },
        semantic: {
          success: 'var(--semantic-success)',
          'success-bg': 'var(--semantic-success-bg)',
          'success-border': 'var(--semantic-success-border)',
          'success-text': 'var(--semantic-success-text)',
          warning: 'var(--semantic-warning)',
          'warning-bg': 'var(--semantic-warning-bg)',
          'warning-border': 'var(--semantic-warning-border)',
          'warning-text': 'var(--semantic-warning-text)',
          error: 'var(--semantic-error)',
          'error-bg': 'var(--semantic-error-bg)',
          'error-border': 'var(--semantic-error-border)',
          'error-text': 'var(--semantic-error-text)',
          info: 'var(--semantic-info)',
          'info-bg': 'var(--semantic-info-bg)',
          'info-border': 'var(--semantic-info-border)',
          'info-text': 'var(--semantic-info-text)',
          live: 'var(--semantic-live)',
          'live-bg': 'var(--semantic-live-bg)',
          'live-border': 'var(--semantic-live-border)',
          breaking: 'var(--semantic-breaking)',
          'breaking-bg': 'var(--semantic-breaking-bg)',
          'breaking-border': 'var(--semantic-breaking-border)',
          sponsored: 'var(--semantic-sponsored)',
          'sponsored-bg': 'var(--semantic-sponsored-bg)',
          'sponsored-border': 'var(--semantic-sponsored-border)',
          'sponsored-text': 'var(--semantic-sponsored-text)',
          link: 'var(--semantic-link)',
          'link-hover': 'var(--semantic-link-hover)',
        },
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-bright': 'var(--accent-bright)',
        'accent-bright-hover': 'var(--accent-bright-hover)',
        // Semantic tokens (mapped to CSS vars)
        bg:         'var(--bg)',
        'bg-alt':   'var(--bg-alt)',
        fg:         'var(--fg)',
        'fg-muted': 'var(--fg-muted)',
        'fg-subtle':'var(--fg-subtle)',
        border:     'var(--border)',
        'card-bg':  'var(--card-bg)',
        'card-border': 'var(--card-border)',
        'nav-bg':   'var(--nav-bg)',
        'footer-bg':'var(--footer-bg)',
        surface: {
          page: 'var(--surface-page)',
          section: 'var(--surface-section)',
          card: 'var(--surface-card)',
          'card-hover': 'var(--surface-card-hover)',
          nav: 'var(--surface-nav)',
          'nav-text': 'var(--surface-nav-text)',
          footer: 'var(--surface-footer)',
          panel: 'var(--surface-panel)',
          input: 'var(--surface-input)',
          overlay: 'var(--surface-overlay)',
          inverse: 'var(--surface-inverse)',
          'inverse-text': 'var(--surface-inverse-text)',
          'card-border': 'var(--surface-card-border)',
          'card-border-hover': 'var(--surface-card-border-hover)',
          divider: 'var(--surface-divider)',
        },
      },
      fontFamily: {
        editorial: ['var(--font-fraunces)', 'Fraunces', 'Georgia', 'serif'],
        ui:        ['var(--font-instrument-sans)', 'Instrument Sans', 'system-ui', 'sans-serif'],
        sans:      ['var(--font-instrument-sans)', 'Instrument Sans', 'system-ui', 'sans-serif'],
        mono:      ['var(--font-space-mono)', 'Space Mono', 'ui-monospace', 'monospace'],
        accent:    ['var(--font-space-mono)', 'Space Mono', 'ui-monospace', 'monospace'],
        display:   ['var(--font-fraunces)', 'Fraunces', 'Georgia', 'serif'],
        body:      ['var(--font-instrument-sans)', 'Instrument Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs:      'var(--text-xs)',
        sm:      'var(--text-sm)',
        base:    'var(--text-base)',
        lg:      'var(--text-lg)',
        xl:      'var(--text-xl)',
        '2xl':   'var(--text-2xl)',
        '3xl':   'var(--text-3xl)',
        '4xl':   'var(--text-4xl)',
        '5xl':   'var(--text-5xl)',
        display: 'var(--text-display)',
        watermark: 'var(--text-watermark)',
      },
      lineHeight: {
        tight:   'var(--leading-tight)',
        snug:    'var(--leading-snug)',
        normal:  'var(--leading-normal)',
        relaxed: 'var(--leading-relaxed)',
        prose:   'var(--leading-prose)',
      },
      letterSpacing: {
        tight:  'var(--tracking-tight)',
        wide:   'var(--tracking-wide)',
        wider:  'var(--tracking-wider)',
        label:  'var(--tracking-label)',
      },
      boxShadow: {
        xs:    'var(--shadow-xs)',
        sm:    'var(--shadow-sm)',
        md:    'var(--shadow-md)',
        lg:    'var(--shadow-lg)',
        xl:    'var(--shadow-xl)',
        card:  'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        nav:   'var(--shadow-nav)',
        dropdown: 'var(--shadow-dropdown)',
        hover: 'var(--shadow-hover)',
        none:  'var(--shadow-none)',
      },
      borderRadius: {
        sm:   'var(--radius-sm)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        card: 'var(--radius-card)',
        full: 'var(--radius-full)',
      },
      animation: {
        ticker:     'ticker 28s linear infinite',
        'fade-in':  'dsFadeIn var(--motion-moderate) var(--ease-editorial) forwards',
        'slide-up': 'dsSlideUp var(--motion-editorial) var(--ease-editorial) forwards',
      },
      transitionDuration: {
        instant: 'var(--motion-instant)',
        fast: 'var(--motion-fast)',
        base: 'var(--motion-base)',
        moderate: 'var(--motion-moderate)',
        editorial: 'var(--motion-editorial)',
        slow: 'var(--motion-slow)',
        dramatic: 'var(--motion-dramatic)',
      },
      transitionTimingFunction: {
        editorial: 'var(--ease-editorial)',
        out: 'var(--ease-out)',
        snap: 'var(--ease-snap)',
      },
      keyframes: {
        ticker: {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
